### ISSUE TITLE
Question: ManicDigger mod

### ISSUE THREAD

**Issue by joshi1999** [MrRar/MrRar.github.io#1]
Hello MrRar!

I saw your Manic Digger Mod with more Blocks on your Github webpage. So I want to ask: Am I alowed to use your "flags" in the official game(CaptureTheFlag, https://github.com/manicdigger/manicdigger/pull/248)?

Rergards
joshi1999

**Comment by MrRar** [comment]
You are absolutely welcome!

**Comment by joshi1999** [comment]
Ok, thank you very much :)
